export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const FILTER_CATEGORY = "FILTER_CATEGORY";
export const FILTER_TYPE = "FILTER_TYPE";
export const FILTER_ID = "FILTER_ID";
export const FILTER_SEARCH = "FILTER_SEARCH";
export const TRANSLATE = "TRANSLATE";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const CLEAR_FILTERED = "CLEAR_FILTERED";
